version: '3.7'

# restart: on-failure
services:
  nodejs:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nodejs
    expose:
      - '5001'
    ports:
      - 5001:5001
    volumes:
      - ./public:/app/public
      - ./app/logs:/app/app/logs
    env_file:
      - .env.example
    networks:
      - bangkitnetwork
    depends_on:
      mysqldb:
        condition: service_healthy
  mysqldb:
    image: mariadb:10.4.25
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql_docker:/var/lib/mysql
      - ./mysql_docker_custom:/etc/mysql/conf.d
      - ./mysql_docker_init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: satuduatiga
      MYSQL_DATABASE: p_bangkit
      MYSQL_USER: bangkit
      MYSQL_PASSWORD: satuduatiga
    ports:
      - '3306:3306'
    restart: always
    healthcheck:
      test: "exit 0"
    networks:
      - bangkitnetwork

  phpmyadmin:
    image: phpmyadmin:5.1.1
    container_name: phpmyadmin
    restart: always
    ports:
      - 8181:80
    environment:
      PMA_ARBITRARY: 1
      PMA_PORTS: 3306
      PMA_HOST: mysqldb
    networks:
      - bangkitnetwork

networks:
  bangkitnetwork:
    external: true